### ISSUE TITLE
Convert between sophia::term::iri::Iri and sophia::iri:Iri?

### ISSUE THREAD

**Issue by KonradHoeffner** [pchampin/sophia_rs#118]
I am confused by the different Iri structs in Sophia: `sophia::iri::Iri` and `sophia::iri::IriBox` vs `sophia::term::iri::Iri` and hope someone an explain to me:

1. Why are there two different types with the same name (Iri) in the same library?
2. Why is there a `sophia::iri::IriBox` but no `sophia::term::iri::IriBox`?
3. Is it possible to convert between the three without going through Strings?

My use case is that I query a graph for triples using `triples_with_s` and then want to save the properties of `triple.p()` into a `Map<IriBox,String>` but iri.boxed() fails with  `method not found in &sophia::term::iri::Iri<Arc<str>>`.

**Comment by pchampin** [comment]
The current state of IRIs in Sophia is a bit of a mess, as I already described [here](https://github.com/pchampin/sophia_rs/discussions/112#discussioncomment-2068543) -- and I can never apologize enough for it. :confused:

If you know for sure that your predicates are absolute IRIs (which is the case if you parse standard RDF, as opposed to the [generalized RDF] supported by Sophia), then you can build your `IriBox` like this:
```rust
IriRefBox::new_unchecked(triple.p().value().into())
```

**Comment by KonradHoeffner** [comment]
Thanks, that is very helpful! I converted my usage of `sophia::term::iri::Iri` to `sophia::iri::Iri`.
