### ISSUE TITLE
`percent_encoding` becomes private in `url`>=2.0.0

### ISSUE THREAD

**Issue by pchampin** [pchampin/sophia_rs#12]
...and the XML parser uses it, which prevents us from upgrading the dependency to `url` beyond 1.7.2. @althanos, could you please have look at it and see if we can get rid of this? Thanks in advance...

**Comment by althonos** [comment]
I don't think we need to use the exact same version as the `url` crate, so this could be resolved
simply by adding `percent-encoding` as a dependency. PR on the way.
