### ISSUE TITLE
please publish alpha version on crates.io

### ISSUE THREAD

**Issue by KonradHoeffner** [pchampin/sophia_rs#132]
I tried to publish the alpha version of HDT, which depends on sophia 0.8.0-alpha, to crates.io but it was denied because it does not accept git dependencies.
Would it be possible to publish something like sophia 0.8.0-alpha.0 on crates.io so it can be used as a dependency?
And is there a timeframe for when 0.8.0 non-alpha will be released?

**Comment by pchampin** [comment]
>  And is there a timeframe for when 0.8.0 non-alpha will be released?

I'd rather not make any promise, but I should have a little more time to progress on that now.

**Comment by KonradHoeffner** [comment]
Thanks! I'm using it straight away :-)
