### ISSUE TITLE
version conflict with MownStr

### ISSUE THREAD

**Issue by KonradHoeffner** [pchampin/sophia_rs#133]
I use your mownstr library in the latest version 0.1.3 but it when I also depend on Sophia 0.8.0-alpha I get a build error because that version of Sophia points to a specific git commit and the two mownstr versions don't match. I can somewhat work around that by directly depending on the MownStr inside Sophia but that stops working when I activate a feature gate that removes the sophia dependency.
Would it be possible to point to a non-git dependency of MownStr inside Sophia?

**Comment by pchampin** [comment]
fixed by https://github.com/pchampin/sophia_rs/commit/0fffed5d9b58d6bf7424f6d86e8c3d1430bed1e9
