### ISSUE TITLE
Relax inner error trait bounds for `StreamError`

### ISSUE THREAD

**Issue by damooo** [pchampin/sophia_rs#135]
Currently `StreamError`'s variants `SourceErr`, `SinkErr` expects inner value to implement `std::error::Error`. Many errors may not implement that trait like `anyhow::Error`. There seems no requirement for that bound.

**Comment by pchampin** [comment]
There is an implicit requirement: `StreamError` itself implements `std::error::Error`, and relies on its inner error to do so.
Removing this would have an impact on other types...

For me, it seems natural that error types should implement `std::error::Error`. The [reason](https://github.com/dtolnay/anyhow/issues/136#issuecomment-758897238) for `anyhow::Error` to not implement this trait looks more like a technical constraint than a conceptual choice. And a [workaround](https://github.com/dtolnay/anyhow/issues/136#issuecomment-758976008) is proposed.
