### ISSUE TITLE
Implement `std::iter::Extend` for provided `Graph`/`Dataset` implementations

### ISSUE THREAD

**Issue by damooo** [pchampin/sophia_rs#138]
[`std::iter::Extend`](https://doc.rust-lang.org/std/iter/trait.Extend.html) allows to extend collections with iterators / streams that produce same type of items.

Though there are `CollectableGraph` and `CollectableDataset`, they won't work with methods provided by `futures::stream::TryStreamExt` etc to consume from non blocking streams.

Currently `DatasetAsGraph`, `UnionGraph`, `FastGraph` etc implementations are painful to construct from async streams. while `HashSet`/`Vec` are trivial as they implement extend.

**Comment by pchampin** [comment]
> [`std::iter::Extend`](https://doc.rust-lang.org/std/iter/trait.Extend.html) allows to extend collections with iterators / streams that produce same type of items.

There is an `insert_all` method in [`MutableGraph`](https://docs.rs/sophia_api/0.8.0-alpha.1/sophia_api/graph/trait.MutableGraph.html#method.insert_all) and [`MutableDataset`](https://docs.rs/sophia_api/0.8.0-alpha.1/sophia_api/dataset/trait.MutableDataset.html#method.insert_all) that plays a similar role.

Some implementations of `Graph` and `Dataset` already implement `Extend` (namely those based on `Vec` and `HashMap`). It would be possible to make other implementations (e.g. `inmem::FastGraph`) implement `Extend`, but generally, `insert_all` is more flexible (it works with any impl of `Triple`).

Do you have a use-case where using `Extend::extend` would be superior to using `Graph::insert_all`?

> Though there are `CollectableGraph` and `CollectableDataset`, they won't work with methods provided by `futures::stream::TryStreamExt` etc to consume from non blocking streams.

As discussed in #134, Sophia is currently focused on "sync" Rust. I suggest we continue discussing this on #134.

> Currently `DatasetAsGraph`, `UnionGraph`, `FastGraph` etc implementations are painful to construct from async streams. while `HashSet`/`Vec` are trivial as they implement extend.

I don't get the link between async streams and the [`Extend`](https://doc.rust-lang.org/std/iter/trait.Extend.html) trait (which is about sync iterators!).

Note that you should not have to create DatasetAsGraph`s nor `UnionGraph`s "manually":
* `DatasetAsGraph`s are constructed via the [`Dataset::graph`](https://docs.rs/sophia_api/0.8.0-alpha.1/sophia_api/dataset/trait.Dataset.html#method.graph) and [`Dataset::graph_mut`](https://docs.rs/sophia_api/0.8.0-alpha.1/sophia_api/dataset/trait.Dataset.html#method.graph_mut) methods
* `UnionGraph`s are constructed via the [`Dataset::union_graph`](https://docs.rs/sophia_api/0.8.0-alpha.1/sophia_api/dataset/trait.Dataset.html#method.union_graph) and [`Dataset::into_union_graph`](https://docs.rs/sophia_api/0.8.0-alpha.1/sophia_api/dataset/trait.Dataset.html#method.into_union_graph) method

**Comment by damooo** [comment]
> DatasetAsGraphs are constructed via the [Dataset::graph](https://docs.rs/sophia_api/0.8.0-alpha.1/sophia_api/dataset/trait.Dataset.html#method.graph) and [Dataset::graph_mut](https://docs.rs/sophia_api/0.8.0-alpha.1/sophia_api/dataset/trait.Dataset.html#method.graph_mut) methods

Yes, i tried them first. But the method signature require bounds of `T: for<'x> [Term](https://docs.rs/sophia_api/0.8.0-alpha.1/sophia_api/term/trait.Term.html)<BorrowTerm<'x> = [DTerm](https://docs.rs/sophia_api/0.8.0-alpha.1/sophia_api/dataset/type.DTerm.html)<'x, Self>> + 'static,` for `T` in `GraphName`, which was not possible in my case with few generic interactions.

It gets sometimes complicated due to GATs and lack of functionality to constrain a GAT value, as in [this post](https://sabrinajewson.org/blog/the-better-alternative-to-lifetime-gats#where-real-gats-fall-short), and [this rfc](https://github.com/tema3210/rfcs/blob/extended_hrtbs/text/3621-extended_hrtb.md)

**Comment by pchampin** [comment]
> Sorry for spamming this issue, it would also be great to have `DatasetGraph` to implement `SetGraph` when underlying `Dataset` implements `SetDataset`.

Very good point. Could you please open a dedicated issue for this? And/or even better, a PR ? :wink:

**Comment by pchampin** [comment]
> > DatasetAsGraphs are constructed via the [Dataset::graph](https://docs.rs/sophia_api/0.8.0-alpha.1/sophia_api/dataset/trait.Dataset.html#method.graph) and [Dataset::graph_mut](https://docs.rs/sophia_api/0.8.0-alpha.1/sophia_api/dataset/trait.Dataset.html#method.graph_mut) methods
> 
> Yes, i tried them first. But the method signature require bounds of `T: for<'x> Term<BorrowTerm<'x> = DTerm<'x, Self>> + 'static,` for `T` in `GraphName`, which was not possible in my case with few generic interactions.

If you need a graph with a different type of `Term`s than the underlying dataset, then you need to copy the corresponding data in a separate graph (e.g. a `Vec<[Term; 3]>` or a `FastGraph`), you should *not* try using `DatasetAsGraph` for this.

But granted, this is not clear from the documentation of `DatasetAsGraph`, which should be improved in that line.

**Comment by pchampin** [comment]
Are you ok to close this issue (opening new ones for the most specific questions above, if needed)?
