### ISSUE TITLE
Documentation in the README

### ISSUE THREAD

**Issue by udp** [pchampin/sophia_rs#145]
The README has License, Citation, Testing, History... but where is the link to the docs ??!!

**Comment by pchampin** [comment]
It is in the "docs" badge at the top ;)

But granted, this is a bit hidden... Funnily enough, I pushed a commit today (88d31df), before I saw your issue, which [adds a more explicit link to the doc](https://github.com/pchampin/sophia_rs/commit/88d31df4d5145a6ae9820eed0f39d3637a695df5#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R31).
