### ISSUE TITLE
Add back query support

### ISSUE THREAD

**Issue by damooo** [pchampin/sophia_rs#146]
Previous versions has a [basic query](https://docs.rs/sophia/latest/sophia/query/enum.Query.html) implementation. Which is highly useful. But is removed in current version.

`Manas` used it to [implement n3-solid-insert-delete-patch](https://github.com/manomayam/manas/blob/main/fcrates/rdf_utils/src/patch/solid_insert_delete/mod.rs) support. Currently it copied query code from previous version into the same `rdf_utils` package, and uses that. If sophia provides it natively, it would be great.

**Comment by pchampin** [comment]
that's a good point. When I started the v0.8 refactoring, I first removed all the non-essential crates, adding them back gradually. I'll consider adding this one sooner rather than later.

**Comment by damooo** [comment]
Sorry for messing with issue.

Indeed that would also be great.

To be frank, it will also enable sparql-update support. https://github.com/manomayam/manas/issues/36

**Comment by pchampin** [comment]
there it is: https://crates.io/crates/sophia_sparql
enjoy :)

NB: for sparql-update, we are not there yet 😅
