### ISSUE TITLE
Issue casting string to literal with custom datatype using `*`

### ISSUE THREAD

**Issue by vemonet** [pchampin/sophia_rs#148]
As found in the [docs](https://pchampin.github.io/sophia_rs/ch02_rdf_terms.html) I tried to create a `xsd:date` literal by running:

```rust
let lit_date = "2023-11-15" * xsd::date;
```

But I am getting this error from the compiler:

> mismatched types
> expected struct `sophia::sophia_api::term::LanguageTag<&str>`
>   found struct `sophia::sophia_api::ns::NsTerm<'static>`

I also tried to do this from within the `sophia_rs` project (by cloning it, and doing this datatype casting somewhere in the tests), and it did not throw the error. 

I am not sure if there is something missing in the code (maybe a trait that needs to be public?), or if I am missing something in my code (like an import?)

**Comment by pchampin** [comment]
This is currently only available from the github version; it is not included on the latest released version on crates.io. Sorry for the confusion.
