### ISSUE TITLE
rio_* crates are not actively maintained - maybe instead use oxrdf

### ISSUE THREAD

**Issue by jonassmedegaard** [pchampin/sophia_rs#175]
The maintainer of rio_api, rip_turtle and rio_xml [no longer actively maintain those packages](https://github.com/oxigraph/rio/issues/142) and has shifted to instead use component from his own [Oxigraph](https://github.com/oxigraph/oxigraph) project - e.g. [oxrdf](https://github.com/oxigraph/oxigraph/tree/main/lib/oxrdf).

Please consider switching from rio_* to ox* crates.

**Comment by pchampin** [comment]
Thanks for reporting this issue. 
Moving to ox* crate is indeed planned, and covered by #162.
