### ISSUE TITLE
Add 'help wanted' issues

### ISSUE THREAD

**Issue by MattesWhite** [pchampin/sophia_rs#18]
`sophia` is the most mature and active developed crate for RDF and linked data at the moment.
However, there is still a long way to go.
Saddly, it seems you don't have much time to work on it.

I realy want this crate to succeed and would like to contribute to it.
But I don't want to mess up your plans.
Therefore, I suggest that you add add some 'help wanted' or 'todo' issues or maybe some milestones to define the long-term goals (like adding SPARQL support?).
This will make it easier for me and others to contribute to this crate.

**Comment by pchampin** [comment]
That's a great idea... I'll do that. Thanks for your support and encouragements.

**Comment by pchampin** [comment]
Here are a few :)
I'll try to make a habit of this, to help the community help me :)
