### ISSUE TITLE
please create a new release

### ISSUE THREAD

**Issue by KonradHoeffner** [pchampin/sophia_rs#181]
The current release 0.8.0 is 9 months old, and I would like to also update the MownStr dependency in the hdt library, which requires the newest state of Sophia.
Is it possible to publish a new release, e.g. 0.8.1, with the current state on crates.io?

**Comment by mkatychev** [comment]
Agreed, the fix to mownstr 0.3 warrants a new version

**Comment by pchampin** [comment]
fair enough...
However, given the number of (breaking) changes that occurred since 0.8.0, I would rather call this new release 0.9.0 -- and push the [pending changes on the 0.9 milestone](https://github.com/pchampin/sophia_rs/milestone/2) to 0.10.

Would that work for you?

**Comment by mkatychev** [comment]
Works for me

**Comment by KonradHoeffner** [comment]
Works for me too!

**Comment by pchampin** [comment]
sorry for the delay, but I was not too far from completing the other issues of the 0.9 milestone, so I thought it was better to do them all. 0.9 is now released, which depends on mownstr 0.3 and is hopefully UB-free!
