### ISSUE TITLE
Sophia 0.9 triples_matching return signature changes: best way to handle dynamic return types?

### ISSUE THREAD

**Issue by KonradHoeffner** [pchampin/sophia_rs#184]
Sorry if this is trivial to Rust experts but I ran into trouble refactoring the Sophia Graph implementation of HDT for the 0.9 changes so I just wanted to ask if there is an obvious solution to this:

The new return type signatures of triples and triples_matching now contain "impl Iterator<...>" but hdt_rs returns different types of Iterators depending on the pattern for triples_matching, so I have to use Box<dyn Iterator...> as shown below.
However the compiler now gives me `warning: impl trait in impl method signature does not match trait method signature` and advises me to add `#[allow(refining_impl_trait)]` to silence this warning.
However I'm hesitant to do that as I'm not sure if that has some negative consequences for the users. Shall I just silence the compiler or is there some other solution to this?

```
 fn triples_matching<'s, S, P, O>(&'s self, sm: S, pm: P, om: O) -> Box<dyn Iterator<Item=Result<Self::Triple<'s>, Self::Error>>  + 's>  
    where
        S: TermMatcher + 's,
        P: TermMatcher + 's,
        O: TermMatcher + 's,
    {
        let xso = match self.unpack_matcher(&sm, &IdKind::Subject) {
            None => return Box::new(iter::empty()),
            Some(x) => x,
        };
        [...]
        match (xso, xpo, xoo) {
            (Constant(s), Constant(p), Constant(o)) => Box::new(iter::once(Ok([s.0, p.0, o.0]))),
            (Constant(s), Constant(p), Other) => Box::new(
                SubjectIter::with_pattern(&self.hdt.triples, &TripleId::new(s.1, p.1, 0))
       [...]
```

**Comment by pchampin** [comment]
You should be able to replace `Box<dyn Iterator<...> + 's>` by `impl Iterator<...> + 's` in the signatures of your implementation, and this should compile fine without warning.

In Sophia 0.8.0, triple-yielding methods were required to return a boxed trait object. Now, they are allowed to return anything that implements the Iterator trait, which *includes* boxed trait objects. That's why your code should still compile with the new signature.

**Comment by KonradHoeffner** [comment]
I had tried that before but then I get a lot of compile errors because the type in the box is not known at compile time because it depends on the code path that is taken.
For example:

```
error[E0308]: mismatched types
   --> src/hdt_graph.rs:185:65
    |
185 |             (Constant(s), Constant(p), Constant(o)) => Box::new(iter::once(Ok([s.0, p.0, o.0]))),
    |                                                        -------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Empty<Result<[...; 3], ...>>`, found `Once<Result<[HdtTerm; 3], _>>`
    |                                                        |
    |                                                        arguments to this function are incorrect
    |
    = note: expected struct `std::iter::Empty<Result<[HdtTerm; 3], Infallible>>`
               found struct `std::iter::Once<Result<[HdtTerm; 3], _>>`
```

**Comment by pchampin** [comment]
I would try adding ` as Box<dyn Iterator<Item=Result<Self::Triple<'s>, Self::Error>>>` after your first `Box::new` in the match arms, to force the compiler to understand the actual return type.

**Comment by pchampin** [comment]
actually, `as Box<dyn Iterator<Item=_>>` should be sufficient
