### ISSUE TITLE
W3C tests don't pass

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [pchampin/sophia_rs#3]
```rust 
failures:

---- parser::nt::test::w3c_test_suite stdout ----
thread 'parser::nt::test::w3c_test_suite' panicked at 'rdf-tests/ntriples not found, can not check W3C test-suite', sophia/src/parser/nt.rs:597:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- parser::nt::test::w3c_test_suite_generalized stdout ----
thread 'parser::nt::test::w3c_test_suite_generalized' panicked at 'rdf-tests/ntriples not found, can not check W3C test-suite', sophia/src/parser/nt.rs:632:17
```

Who to get w3c_test_suite ?

**Comment by MarcAntoine-Arnaud** [comment]
Thks @pchampin

**Comment by pchampin** [comment]
Sorry, this was indeed lacking proper documentation.

This "fix" is minimalist: you have to manually follow the instructions in the README. If you have ideas to automate this process in a portable way, feel free to reopen the issue.

**Comment by MarcAntoine-Arnaud** [comment]
Hi,

It's a first step.
I wanna to purpose soon the ability to define a `build.rs` file (used by Cargo) to define some function.
And here we can be able to download W3C files (with a local cache for offline developments).

But before doing that I wanna to improve the code quality:
- add Travis CI to test on multi versions of rust
- check Rust code format
- check Rust code with Clippy (to prevent some bad writing)

I have configured that on [yaserde](https://github.com/media-io/yaserde/blob/master/.travis.yml) and it's cool to open source contribution.

**Comment by MarcAntoine-Arnaud** [comment]
I started to create a branch to test CI.
In fact I used the git submodule to retrieve rdf-tests.
