### ISSUE TITLE
Make sophia ready to support external serializers

### ISSUE THREAD

**Issue by MattesWhite** [pchampin/sophia_rs#34]
For now `sophia` only provides serializers for `N-Triples` and `N-Quads`. In order to support further serializers, we must develop an API for them, i.e. traits and some utilities. This contributes to #23.

_When ever triples and graphs are mentioned those can be replaced by quad and dataset respectively. If not mentioned otherwise._

## Steps towards an improved serializer API

- [ ] Make the internals of `Term::Literal` an own type like `IriData` or `BNodeId`. This way it is easier to implement specific serializations for literals.
- [x] Remove the `n3()`-method from `Term`. It can be replaced by introducing a trait, e.g.:

  ```rust
  trait NtSerializableTerm {
      fn nt(&self) -> String;
  }

  impl NtSerializableTerm for Term {
      fn nt(&self) -> String {
          crate::serializer::nt::stringify_term(self)
      }
  }
  ```

  Or at least rename the method properly.
- [x] Provide a trait `Serializer` or several specific one, e.g. `TripleSerializer` and `GraphSerializer`. The first for streams the second for more sophisticated actions (see #17). Some symmetry to the `Parser` trait would be nice.
- [x] Introduce the changes to the NT-serializer.

All points are open to discussion.

**Comment by MattesWhite** [comment]
I started writting my Turtle serializer: https://github.com/MattesWhite/metis-rs

For now it is pretty basic and far from usable but the stream serializer already works (kind of). What stops me from advancing at the moment is the abbreviation of IRI, i.e. how to match against a namespace. Maybe something like 

```rust
impl IriData {
    fn match_ns(&'a self, ns: impl AsRef<str>) -> Option<impl Iterator<Item = &'a Char>>;
}

where in case of a match the `Iterator` holds the left chars so it matches all (non-)suffixed IRIs... 

I can implement this if you want but as said I wait for the serializer API to be merged before continuing my work.
```

**Comment by pchampin** [comment]
> I started writting my Turtle serializer: https://github.com/MattesWhite/metis-rs

Awesome :)

I'm on my way to improve the `stream` API (#38), which will open the way to a cleaner Serializer API (#37). Once this is done, I'd like to release a new version. It's been a long time since the last one, and your crate could depend on a stable version rather than a github link...

Regarding `match_ns`, that's a good idea, with the following changes:
* why not simply accept `&str` for the `ns` parameter?
* I'm guessing you meant `char` and not `Char`
* Why return an iterator of `&'a char`? Why not simply `char`?
* It would make more sense to me to return the *right* chars, i.e. those usable to make the suffix
  (but maybe that's what you meant).

**Comment by pchampin** [comment]
@MattesWhite could you please have a loop at the latest commit 9a97dae ? It introduces a new Serializer API which I think will please you better than my former attempt #37.

**Comment by MattesWhite** [comment]
> [...] I think will please you better than my former attempt [...]

Your right :smile:, nice work. I created a PR, fixing some minor issues.

The only thing left on the initial agenda is now separating the 'kinds of term' into own modules. We already talked about this in #35 . Should I take care about this or do you want to do this on your own?

**Comment by pchampin** [comment]
> Should I take care about this or do you want to do this on your own?

I don't mind if you do ;-)
