### ISSUE TITLE
Make in-memory indexed graphs more generic

### ISSUE THREAD

**Issue by pchampin** [pchampin/sophia_rs#64]
Following the discussion in #55, I realize that some people might be interested in reusing the implementation of `graph::inmem` or `dataset::inmem`, even for types that go 
*beyond* the RDF model (even the generalized on that Sophia supports). For example:

* [Notation 3](https://www.w3.org/community/n3-dev/) (which @MattesWhite is working on)
* [RDF-*](http://olafhartig.de/files/Hartig_AMW2017_RDFStar.pdf)
* Other flavors of [property graphs](https://en.wikipedia.org/wiki/Graph_database#Labeled-property_graph)

Actually, these implementations are rather agnostic to the kind of *terms* they handle, as internally they are just represented by integer indexes. Possibly, this could be factored out in a separate crate (`sophia_igraph`?). And of course, if (some of) the terms they contain can be seen as RDF terms, they could in turn implement the `Graph`/`Dataset` traits...

@BruJu what do you think?

**Comment by MattesWhite** [comment]
As a first step I refactored the core of `TermIndexMap` into a new crate [`indexed-hash-set`](https://crates.io/crates/indexed-hash-set) that basically provides the same core functionality. With this I'll continue my work on #89.

**Comment by pchampin** [comment]
closing this old issue, as my priority with Sophia is less to provide new implementations than to provide good traits that existing implementations can implement, to increase interoperability.

A generic "indexed graph" crate would be a nice thing to have, but it would be better suited outside Sophia.
