### ISSUE TITLE
Promote sophia in the Rust community

### ISSUE THREAD

**Issue by MattesWhite** [pchampin/sophia_rs#78]
Today `sophia` is at an incredible state and the foundations for a powerful RDF framework for Rust are mostly done. However, while there is an increasing amount of people opening issues. The downloads of `sophia` on [crates.io](https://crates.io/crates/sophia) are still under a thousand. I assume we could improve the popularity and attract contributors to `sophia` or even getting people to add crates to the `sophia`-ecosystem if we promote `sophia` more in the Rust community.

For me a start would be:
1. Announcement post for `sophia` v0.6 at URLO.
1. Suggestion for [Crate of the Week](https://users.rust-lang.org/t/crate-of-the-week/2704/792).
1. Post at [Call for Participation](https://users.rust-lang.org/t/twir-call-for-participation/4821/323).

The later two have a chance to be included into [This Week in Rust](https://this-week-in-rust.org/) which is at least for me the mandatory weekly update concerning Rust.

If you wish I could write the posts I don't think this could cause any harm, just wanted to ask for permission first.

**Comment by pchampin** [comment]
Sounds like a great idea. I announced it [on my blog](http://champin.net/blog/2020/sophia-v0.6/)
but arguably it is not as visible as URLO :wink:.

Feel free write the posts -- I confess I didn't have a URLO account until today... Please just mention me (I'm @pchampin there too) so I'll be notified (I guess).
