### ISSUE TITLE
Any plans to use core stable instead of nightly? 

### ISSUE THREAD

**Issue by huhn511** [pchampin/sophia_rs#95]
Hi folks,

this is a really nice project! 

I just found out, that I need to build 'sophia_iri' with Rust nightly. 
Do you have any plans to use Rust stable instead of nightly? 

Best wishes,
huhn

**Comment by pchampin** [comment]
>this is a really nice project!

thanks :)

>I just found out, that I need to build 'sophia_iri' with Rust nightly.

I am very surprised! I am using Rust stable exclusively (1.45.0 at the moment)...
I just tried to build a fresh clone of the repo, and checked with `rustup show` that I am indeed using stable:
```
active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.45.0 (5c1f21c3b 2020-07-13)
```

What toolchain are you using?

**Comment by huhn511** [comment]
Oh sorry, my fault!

Indeed, I did just update Rust and now it works with stable. 

Thanks!
